### ISSUE TITLE
about make_dataset.py

### ISSUE THREAD

**Issue by lijiashan2020** [drorlab/DIPS#8]
Hi,
Thank you for your Open source work, and I have a question, when I run the command:
```
python src/make_dataset.py ./data/DIPS/raw/pdb ./data/DIPS/interim
```
I got error as follow:
```
2022-03-31 21:38:43,233 INFO 186563: making final data set from interim data
2022-03-31 21:49:30,643 INFO 186563: 273661 requested keys, 273661 produced keys, 0 work keys
2022-03-31 21:49:30,712 WARNING 186563: Complex file ./data/DIPS/interim/complexes/complexes.dill already exists!
Traceback (most recent call last):
  File "/data/DIPS/src/make_dataset.py", line 45, in <module>
    main()
  File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/extendplus/jiashan/equidock_public/DIPS/src/make_dataset.py", line 36, in main
    get_pairs = pair.build_get_pairs(type, unbound, get_neighbors, False)
TypeError: build_get_pairs() missing 1 required positional argument: 'full'
```
Could you please help me with this error?
Thanks!

**Comment by lizhenping** [comment]
> Hi, Thank you for your Open source work, and I have a question, when I run the command:
> 
> ```
> python src/make_dataset.py ./data/DIPS/raw/pdb ./data/DIPS/interim
> ```
> 
> I got error as follow:
> 
> ```
> 2022-03-31 21:38:43,233 INFO 186563: making final data set from interim data
> 2022-03-31 21:49:30,643 INFO 186563: 273661 requested keys, 273661 produced keys, 0 work keys
> 2022-03-31 21:49:30,712 WARNING 186563: Complex file ./data/DIPS/interim/complexes/complexes.dill already exists!
> Traceback (most recent call last):
>   File "/data/DIPS/src/make_dataset.py", line 45, in <module>
>     main()
>   File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/extendplus/app/miniconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/extendplus/jiashan/equidock_public/DIPS/src/make_dataset.py", line 36, in main
>     get_pairs = pair.build_get_pairs(type, unbound, get_neighbors, False)
> TypeError: build_get_pairs() missing 1 required positional argument: 'full'
> ```
> 
> Could you please help me with this error? Thanks!

Hi：
You can follow this:
https://github.com/BioinfoMachineLearning/DIPS-Plus/blob/main/project/datasets/builder/make_dataset.py
